services:
  mongo:
    image: mongo:latest
    container_name: ${TODO_DB_HOST}
    environment:
      TODO_DB_USER: ${TODO_DB_USER}
      TODO_DB_PASSWORD: ${TODO_DB_PASSWORD}
      TODO_DB_NAME: ${TODO_DB_NAME}
      
    ports:
      - ${TODO_DB_PORT}:${TODO_DB_PORT}
    volumes:
      - ./initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  app:
    container_name: todo-app
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:${TODO_DB_PORT}
      WAIT_TIMEOUT: "60"
      WAIT_SLEEP_INTERVAL: "2"
      WAIT_HOST_CONNECT_TIMEOUT: "30"
      TODO_DB_USER: ${TODO_DB_USER}
      TODO_DB_PASSWORD: ${TODO_DB_PASSWORD}
      TODO_DB_NAME: ${TODO_DB_NAME}  
      TODO_DB_HOST: ${TODO_DB_HOST}
      TODO_DB_PORT: ${TODO_DB_PORT}
    ports:
      - ${TODO_APP_PORT}:${TODO_APP_PORT}
    build: .
    command: node index.js