services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
      TODO_DB_USER: ${TODO_DB_USER}
      TODO_DB_PASSWORD: ${TODO_DB_PASSWORD}
      TODO_DB_NAME: ${TODO_DB_NAME}
    
    volumes:
      - ./initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro